# Generated by Django 4.2.4 on 2023-09-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_category_product_subcategory_product_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='income',
            table='income',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategory',
        ),
        migrations.AlterModelTable(
            name='tipe',
            table='tipe',
        ),
    ]
